// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDLZcFyfNSuNkXfpryvzAeusBn-ZcbHT4',
    appId: '1:607471003986:web:8610aa4609d7070ed5728b',
    messagingSenderId: '607471003986',
    projectId: 'mashtaly-hu',
    authDomain: 'mashtaly-hu.firebaseapp.com',
    storageBucket: 'mashtaly-hu.appspot.com',
    measurementId: 'G-MDVMMBZ5JN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7yuGX-RJbBlv4KpDHE2kIF0IlTZ2_XO0',
    appId: '1:607471003986:android:257e263a2631da96d5728b',
    messagingSenderId: '607471003986',
    projectId: 'mashtaly-hu',
    storageBucket: 'mashtaly-hu.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnnH6kgXC01Drc5cW7teOgPm698yFPWRs',
    appId: '1:607471003986:ios:427715a74568712cd5728b',
    messagingSenderId: '607471003986',
    projectId: 'mashtaly-hu',
    storageBucket: 'mashtaly-hu.appspot.com',
    iosClientId:
        '607471003986-ia3cai305q2oajapotuf14pj1ahj4cbc.apps.googleusercontent.com',
    iosBundleId: 'com.example.mashtalyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnnH6kgXC01Drc5cW7teOgPm698yFPWRs',
    appId: '1:607471003986:ios:427715a74568712cd5728b',
    messagingSenderId: '607471003986',
    projectId: 'mashtaly-hu',
    storageBucket: 'mashtaly-hu.appspot.com',
    iosClientId:
        '607471003986-ia3cai305q2oajapotuf14pj1ahj4cbc.apps.googleusercontent.com',
    iosBundleId: 'com.example.mashtalyApp',
  );
}
